version: '3'
services:
  crawler-redis:
    image: redis:5-alpine
    ports: 
      - 6379:6379
  critical-crawler:
    image: zkchn/critical-css-crawler:latest
    environment:
      REDIS: //crawler-redis:6379
    ports:
      - 3000:3000